# Generated by Django 6.0.4 on 2026-04-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipttransaction',
            name='file',
            field=models.FileField(upload_to='receipts/'),
        ),
    ]
