# Generated by Django 6.0.4 on 2026-04-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_incometransaction_account_and_more'),
        ('app_main', '0005_remove_scheduleexpense_dayofweek_and_more'),
    ]

    operations = [
    ]
