# Generated by Django 6.0.4 on 2026-04-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_merge_20260419_0407'),
        ('app_main', '0008_alter_itemtransaction_date'),
    ]

    operations = [
    ]
